### ISSUE TITLE
[REQUEST] Persepolis Anomaly logo

### ISSUE THREAD

**Issue by htomasz** [ra100/ingress-logos#2]
It's possible to create Persepolis Anomaly logo?

**Comment by gbrusella** [comment]
Found some in https://www.dropbox.com/sh/lboona3bws639ud/AABiY-3RwncDWh-pZJky8yrKa?dl=0 but don't know the source

**Comment by ra100** [comment]
Thanks @gbrusella, I tried to contact owner of those files.

**Comment by ra100** [comment]
done 4843ccdee03821eee8d7bf199c155e93f585e66a
